In [33]:
import pandas as pd
import json

In [2]:
import pandas as pd

df = pd.read_csv('raw_data/recipes_ingredients.csv')
df.head()

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags
0,71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","[""cherry pie filling"", ""condensed milk"", ""melt...","[""2 (21 ounce) cans cherry pie filling"",""2...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
1,76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"[""corned beef chopped"", ""sauerkraut cold water...","[""1/2-1 lb corned beef, cooked and choppe...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
2,503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"[""unsalted butter"", ""vegetable oil"", ""all - pu...","[""3/4 cup unsalted butter, at room tempera...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ..."
3,418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"[""orange cake mix"", ""instant vanilla pudding"",...","[""1 (18 ounce) pkge.orange cake mix"",""1 (3...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
4,392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"[""butter"", ""brown sugar"", ""granulated sugar"", ...","[""1/2 cup butter, room temperature "",""1/2 ...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course..."

In [3]:
df.info

<bound method DataFrame.info of             id                                               name  \
0        71247                            Cherry Streusel Cobbler
1        76133                    Reuben and Swiss Casserole Bake
2       503816                                   Yam-Pecan Recipe
3       418749                        Tropical  Orange Layer Cake
4       392934  Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...
...        ...                                                ...
500466  173790                              Sausage Meatloaf OAMC
500467  301838       Potato Salad With Olives Capers and Parmesan
500468  130682                        Chocolate Banana Pound Cake
500469  353659              Cheesy Ground Beef and Rice Casserole
500470  510848            Chicken and Dumplings &ndash; Crock Pot

                                              description  \
0       I haven't made this in years, so I'm just gues...
1       I think this is even better than a reuben sand...
2       A lady I work with heard me taking about ZWT a...
3       An easy and delicious cake.  Great for a  summ...
4       I was searching the web for something like thi...
...                                                   ...
500466  I grew up on this meatloaf, and I love it.  It...
500467                                     Cooking Light.
500468  This recipe was passed to me by my mother, and...
500469  This is one of those comfort food dishes I cre...
500470  Fix it and Forget it Lightly – Slow Cooker rec...

                                              ingredients  \
0       ["cherry pie filling", "condensed milk", "melt...
1       ["corned beef chopped", "sauerkraut cold water...
2       ["unsalted butter", "vegetable oil", "all - pu...
3       ["orange cake mix", "instant vanilla pudding",...
4       ["butter", "brown sugar", "granulated sugar", ...
...                                                   ...
500466  ["ground beef", "ground sausage", "celery chop...
500467  ["red potatoes", "fresh ground black pepper", ...
500468  ["butter", "brown sugar", "bananas", "buttermi...
500469  ["ground beef", "medium onion chopped", "brown...
500470  ["chicken cubed", "frozen vegetables", "onion"...

                                          ingredients_raw  \
0       ["2 (21   ounce) cans   cherry pie filling","2...
1       ["1/2-1   lb    corned beef, cooked and choppe...
2       ["3/4  cup    unsalted butter, at room tempera...
3       ["1 (18   ounce)   pkge.orange cake mix","1 (3...
4       ["1/2  cup    butter, room temperature ","1/2 ...
...                                                   ...
500466  ["1   lb    lean ground beef","1/2  lb    grou...
500467  ["3   lbs    small red potatoes","2   tablespo...
500468  ["1   cup    butter (room temperature)","2   l...
500469  ["1 1/2  lbs    ground beef","1   medium    on...
500470  ["1   lb    chicken, cubed ","1   lb    frozen...

                                                    steps  servings  \
0       ["Preheat oven to 375°F.", "Spread cherry pie ...       6.0
1       ["Set oven to 350 degrees F.", "Butter a 9 x 1...       4.0
2       ["Preheat oven to 350°F  In a mixing bowl, usi...       8.0
3       ["In a large mixing bowl, combine the first 6 ...      16.0
4       ["Cream butter and sugars together.", "Blend i...      24.0
...                                                   ...       ...
500466  ["Combine ground beef, sausage, celery, onion,...       6.0
500467  ["Preheat oven to 375°.", "To prepare potatoes...       8.0
500468  ["Preheat oven to 350 degrees.", "Grease and f...      24.0
500469  ["*What I mean by "partly drained" with the mu...       6.0
500470  ["Combine chicken, vegetables, onion and chick...       6.0

       serving_size                                               tags
0         1 (347 g)  ["60-minutes-or-less", "time-to-make", "course...
1         1 (207 g)  ["60-minutes-or-less", "time-to-make", "course...
2         1 (198 g)  ["time-to-make", "course", "main-ingredient", ...
3         1 (191 g)  ["60-minutes-or-less", "time-to-make", "course...
4          1 (26 g)  ["15-minutes-or-less", "time-to-make", "course...
...             ...                                                ...
500466    1 (244 g)  ["time-to-make", "course", "main-ingredient", ...
500467    1 (223 g)  ["time-to-make", "course", "main-ingredient", ...
500468     1 (99 g)  ["time-to-make", "course", "main-ingredient", ...
500469    1 (394 g)  ["60-minutes-or-less", "time-to-make", "prepar...
500470    1 (323 g)  ["course", "preparation", "5-ingredients-or-le...

[500471 rows x 9 columns]>

In [4]:
df.isnull().sum()

id                    0
name                  0
description        2186
ingredients           0
ingredients_raw      35
steps                 0
servings            722
serving_size         35
tags                 35
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.iloc[0]

id                                                             71247
name                                         Cherry Streusel Cobbler
description        I haven't made this in years, so I'm just gues...
ingredients        ["cherry pie filling", "condensed milk", "melt...
ingredients_raw    ["2 (21   ounce) cans   cherry pie filling","2...
steps              ["Preheat oven to 375°F.", "Spread cherry pie ...
servings                                                         6.0
serving_size                                               1 (347 g)
tags               ["60-minutes-or-less", "time-to-make", "course...
Name: 0, dtype: object

In [7]:
import json

df['tags'] = df['tags'].fillna('[]').apply(json.loads)

all_tags = [tag for lista in df['tags'] for tag in lista]

pd.Series(all_tags).value_counts().head(30)

preparation              496606
time-to-make             483507
course                   470603
main-ingredient          348022
dietary                  332195
easy                     263078
occasion                 226727
cuisine                  183717
low-in-something         182366
60-minutes-or-less       155872
main-dish                152459
equipment                122487
30-minutes-or-less       117567
number-of-servings       116125
meat                     114861
4-hours-or-less          113460
desserts                 105877
vegetables               105869
3-steps-or-less          105146
taste-mood                98046
north-american            95330
low-sodium                94489
low-carb                  89268
healthy                   84564
15-minutes-or-less        84516
low-cholesterol           77516
low-calorie               76466
dinner-party              73369
5-ingredients-or-less     71605
low-protein               69889
Name: count, dtype: int64

In [8]:
tag_counts = pd.Series(all_tags).value_counts()

keywords = ['vegan', 'vegetarian', 'gluten', 'dairy', 'nut', 'egg', 'lactose']
for k in keywords:
    matches = tag_counts[tag_counts.index.str.contains(k, case=False)]
    print(matches)

vegan    19919
Name: count, dtype: int64
vegetarian    68955
Name: count, dtype: int64
gluten-free               11637
gluten-free-appetizers        1
Name: count, dtype: int64
eggs-dairy    57622
dairy-free      348
Name: count, dtype: int64
60-minutes-or-less           155872
30-minutes-or-less           117567
15-minutes-or-less            84516
nuts                          13910
coconut                        3215
nut-free                        987
peanut-butter                   798
cookies-and-brownies-nuts         2
coconut-desserts                  1
coconut-cream-pie                 1
peanut-butter-pie                 1
Name: count, dtype: int64
eggs-dairy        57622
eggs              17531
egg-free           9769
eggplant            321
veggie-burgers      143
breakfast-eggs        4
eggs-breakfast        3
egg whites            1
Name: count, dtype: int64
lactose    7737
Name: count, dtype: int64

In [9]:
import ast

def try_parse(x):
    try:
        ast.literal_eval(x)
        return True
    except (ValueError, SyntaxError):
        return False

# Necesitas volver a cargar la columna original si ya la sobrescribiste con listas vacías
# Si ya la sobrescribiste, recarga el CSV original antes de seguir

mask_failed = ~df['ingredients'].apply(try_parse)
df.loc[mask_failed, 'ingredients'].head(5)

53563     ["noodles dry udon spaghetti", "Chinese eggpla...
102611    [\blue bell vanilla " ice cream\, "strawberrie...
191592    ["New Mexico chiles", "dried ancho peppers", "...
215039    [\sweet potatoes yellow - flesh sweet potatoes...
285574    ["oats", "boiling water", "flax seed meal flou...
Name: ingredients, dtype: object

In [10]:
df = pd.read_csv('raw_data/recipes_ingredients.csv')  # recarga fresca, obligatorio antes de reintentar

import re, ast

def parse_ingredients_v2(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        matches = re.findall(r'"([^"]*)"|\\(.*?)\\', x)
        return [a if a else b for a, b in matches]

df['ingredients'] = df['ingredients'].apply(parse_ingredients_v2)

(df['ingredients'].apply(len) == 0).sum()

np.int64(10707)

In [11]:
df.loc[102611, 'ingredients']

['blue bell vanilla " ice cream',
 'strawberries',
 'plain flavored yoplat yogurt',
 'grape juice']

In [12]:
(df['ingredients'].apply(len) == 0).sum()

np.int64(10707)

In [13]:
import re, ast

df = pd.read_csv('raw_data/recipes_ingredients.csv')

def parse_ingredients_v2(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        matches = re.findall(r'"([^"]*)"|\\(.*?)\\', x)
        return [a if a else b for a, b in matches]

df['ingredients'] = df['ingredients'].apply(parse_ingredients_v2)

print(df.loc[102611, 'ingredients'])
print((df['ingredients'].apply(len) == 0).sum())

['blue bell vanilla " ice cream', 'strawberries', 'plain flavored yoplat yogurt', 'grape juice']
10707

In [14]:
mask_still_empty = df['ingredients'].apply(len) == 0

# Trae el texto ORIGINAL de esas filas (recarga fresca para comparar)
df_check = pd.read_csv('raw_data/recipes_ingredients.csv')

for val in df_check.loc[mask_still_empty, 'ingredients'].head(5):
    print(repr(val))
    print('---')

'[]'
---
'[]'
---
'[]'
---
'[]'
---
'[]'
---

In [15]:
df_check.loc[mask_still_empty, ['ingredients', 'ingredients_raw']].head(5)

    ingredients                                    ingredients_raw
37           []  ["  pineapple","  banana","  jackfruit","  sou...
55           []  ["1 (470   g) can   mangoes in syrup","1/2  te...
98           []  ["1 (12   ounce) bag   broccoli slaw mix","2  ...
144          []  ["1 (12   ounce) package   butterscotch chips"...
155          []  ["8   ounces    spinach fettuccine, uncooked "...

In [16]:
print(repr(df_check.loc[37, 'ingredients_raw']))

'["  pineapple","  banana","  jackfruit","  soursop","  mango","  rambutans","  lychee","  pommelo","  star fruit","  passion fruit","  guava","  papaya","  oranges or   orange juice"]'

In [17]:
df = pd.read_csv('raw_data/recipes_ingredients.csv')

def parse_list_safe(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        matches = re.findall(r'"([^"]*)"|\\(.*?)\\', x)
        return [a if a else b for a, b in matches]

df['ingredients'] = df['ingredients'].apply(parse_list_safe)
df['ingredients_raw'] = df['ingredients_raw'].fillna('[]').apply(parse_list_safe)

# Donde ingredients está vacío, usa ingredients_raw como respaldo (limpiando espacios)
mask_empty = df['ingredients'].apply(len) == 0
df.loc[mask_empty, 'ingredients'] = df.loc[mask_empty, 'ingredients_raw'].apply(
    lambda lst: [item.strip() for item in lst]
)

# Conteo final
(df['ingredients'].apply(len) == 0).sum()

np.int64(35)

In [18]:
df = df[df['ingredients'].apply(len) > 0].reset_index(drop=True)
df.shape

(500436, 9)

In [19]:
df['description'] = df['description'].fillna('')
df['servings'] = df['servings'].fillna(df['servings'].median())

df.isnull().sum()

id                 0
name               0
description        0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [20]:
restricciones = {
    'is_vegan': 'vegan',
    'is_vegetarian': 'vegetarian',
    'is_gluten_free': 'gluten-free',
    'is_dairy_free': 'dairy-free',
    'is_lactose_free': 'lactose',
    'is_nut_free': 'nut-free',
    'is_egg_free': 'egg-free',
}

for columna, tag in restricciones.items():
    df[columna] = df['tags'].apply(lambda t: tag in t)

tiempos = {
    'quick_60min': '60-minutes-or-less',
    'quick_30min': '30-minutes-or-less',
    'quick_15min': '15-minutes-or-less',
}

for columna, tag in tiempos.items():
    df[columna] = df['tags'].apply(lambda t: tag in t)


df[list(restricciones.keys()) + list(tiempos.keys())].sum()

is_vegan            19919
is_vegetarian       68955
is_gluten_free      11637
is_dairy_free         348
is_lactose_free      7737
is_nut_free           987
is_egg_free          9769
quick_60min        155872
quick_30min        117567
quick_15min         84516
dtype: int64

In [21]:
df.to_csv('raw_data/recipes_clean.csv', index=False)

In [22]:
print(df.loc[0, 'ingredients_raw'])

['2 (21   ounce) cans   cherry pie filling', '2       eggs', '1 (14   ounce) can   sweetened condensed milk (not evaporated)', '1/4  cup   melted margarine', '1/2  teaspoon    cinnamon', '1/4  teaspoon    nutmeg', '1/2  cup   firmly packed light brown sugar', '1/2  cup    self-rising flour', '1/4  cup    margarine', "1/2  cup   chopped nuts (chef's choice)", '1/2  cup    quick-cooking oats', '  butter-flavored cooking spray']

In [23]:
all_ingredients = (
    df["ingredients"]
    .explode()
    .dropna()
    .str.strip()
    .str.lower()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

all_ingredients

0
1         % - cacao bittersweet chocolate
2                       % pineapple juice
3                 % pink grapefruit juice
4                                       &
                       ...
292420                    zuchinni squash
292421                     zucunni squash
292422                     zwieback toast
292423              zwieback toast crumbs
292424                       ’ pita chips
Name: ingredients, Length: 292425, dtype: object

In [24]:
all_ingredients

0
1         % - cacao bittersweet chocolate
2                       % pineapple juice
3                 % pink grapefruit juice
4                                       &
                       ...
292420                    zuchinni squash
292421                     zucunni squash
292422                     zwieback toast
292423              zwieback toast crumbs
292424                       ’ pita chips
Name: ingredients, Length: 292425, dtype: object

In [25]:
df['ingredients']

0         [cherry pie filling, condensed milk, melted ma...
1         [corned beef chopped, sauerkraut cold water, s...
2         [unsalted butter, vegetable oil, all - purpose...
3         [orange cake mix, instant vanilla pudding, ora...
4         [butter, brown sugar, granulated sugar, milk, ...
                                ...
500431    [ground beef, ground sausage, celery chopped, ...
500432    [red potatoes, fresh ground black pepper, virg...
500433    [butter, brown sugar, bananas, buttermilk, van...
500434    [ground beef, medium onion chopped, brown rice...
500435    [chicken cubed, frozen vegetables, onion, chic...
Name: ingredients, Length: 500436, dtype: object

In [26]:
df["ingredient_raw_count"] = df["ingredients_raw"].str.len()

In [27]:
df["ingredient_raw_count"].value_counts()

ingredient_raw_count
8     52851
9     51663
7     50506
10    48245
6     44944
11    41246
5     36987
12    33609
13    26138
4     24279
14    19739
15    15149
3     12908
16    10827
17     7875
18     5448
2      4369
19     3913
20     2834
21     1996
22     1333
23      954
24      717
25      502
26      346
27      253
28      187
29      136
30      101
32       75
31       75
33       40
34       31
35       28
1        23
38       20
36       18
37       16
39       12
40       10
41       10
43        6
44        5
42        5
45        4
50        1
47        1
46        1
Name: count, dtype: int64

In [28]:
df[df["ingredient_raw_count"] == 8]

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags,is_vegan,is_vegetarian,is_gluten_free,is_dairy_free,is_lactose_free,is_nut_free,is_egg_free,quick_60min,quick_30min,quick_15min,ingredient_raw_count
13,233067,Crepes for Two,I'm only cooking for two now and always on the...,"[milk, vegetable oil, powdered sugar, orange m...","[1/2 cup flour, 3/4 cup milk, 1 ...","[""Combine flour, milk, eggs, and oil and salt....",2.0,1 (243 g),"[""15-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,False,True,8
41,381617,Cheesy Jalapeno Bread (Abm),This came from thatsmyhome.com They have a TON...,"[bread flour, oil, warm water, jalapeno pepper...","[2 1/2 teaspoons yeast, 3 cups bread ...","[""Place yeast, flour, salt, sugar, oil, water ...",12.0,1 (67 g),"[""time-to-make"", ""course"", ""preparation"", ""hea...",False,False,False,False,False,False,False,False,False,False,8
50,505744,Hot and Sour Mushroom Soup,This is from galanga.com. which features recip...,"[vegetable stock, pepper sauce, lemongrass, ka...","[1 cup vegetable stock, 1 teaspoon p...","[""Add all recipes in a pot, except for the chi...",3.0,1 (62 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,True,False,False,False,False,False,True,False,False,8
62,293571,Faye's Broiled Hamburgers,Friends love them - I hope you do too.If freez...,"[ground beef, onion, boiling water, beef bouil...","[5 lbs lean ground beef, 1 teaspoon ...","[""Dissolve the beef bouillon in the water. Al...",24.0,1 (128 g),"[""30-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,True,False,8
66,343158,Maple Meltaways,"Ohhh, these delicate cookies are always sought...","[butter, granulated sugar, maple syrup, maple ...","[1 1/2 cups unsalted butter, 1 1/3 cups ...","[""Cream together butter and sugar."", ""Add mapl...",1.0,1 (1705 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,True,False,False,False,False,False,True,False,False,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500359,64271,Hearty Oat &amp; Walnut Bread (bread machine),"I love walnuts, and I try to add it to most of...","[bread flour, quick oats, brown sugar, walnuts...","[1 1/2 teaspoons yeast, 3 1/4 cups bre...","[""Place ingredients in machine according to yo...",1.0,1 (923 g),"[""weeknight"", ""time-to-make"", ""course"", ""prepa...",True,True,False,False,False,False,False,False,False,False,8
500367,75849,Iron Rich Vegetable Juice,From the Food Facts column of the Thursday mag...,"[pepper, beet, carrots, fresh spinach, tomatoe...","[1 glass water, salt, black pepper, 1...","[""To make this healthy morning drink, put all ...",2.0,1 (366 g),"[""30-minutes-or-less"", ""time-to-make"", ""course...",True,True,False,False,False,False,False,False,True,False,8
500373,217664,Jasper's Bourbon Creamed Corn,"I found this on the net, and although I'm not ...","[shallot, garlic cloves minced, red bell peppe...","[1/4 cup butter, 1 cup shallot, chopp...","[""Melt butter in heavy large skillet over medi...",6.0,1 (286 g),"[""30-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,True,False,8
500404,33705,Dill Mustard Pickles,I took a fabulous recipe (credit to Lali) and ...,"[2 cups prepared mustard, 2 cups sal...","[2 cups prepared mustard, 2 cups sal...","[""Scrub cucumbers and place in the above mixtu...",1.0,1 (15863 g),"[""30-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,True,False,8
500418,436400,Terriyaki Sauce,I got this recipe online and can't remember wh...,"[soy sauce, water, ginger, garlic powder, brow...","[1/4 cup soy sauce, 1 cup water, 1/2 ...","[""1. Mix all but cornstarch and 1/4c water in ...",1.0,1 (476 g),"[""15-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,False,True,8

In [29]:
df.iloc[13,4]

['1/2  cup    flour',
 '3/4  cup    milk',
 '1       egg',
 '1/2  teaspoon    vegetable oil',
 '1   dash    salt',
 '1/4  cup    powdered sugar',
 '1/2  cup    orange marmalade',
 '  oil or   nonstick cooking spray']

In [30]:
df.iloc[14,4]

['2   lbs   boneless beef stew meat, cut into 1-inch cubes ',
 '12   small    white onions',
 '4       whole cloves',
 '2   tablespoons    brown sugar',
 '1 1/2  teaspoons    salt',
 '1/2  teaspoon   bottled Kitchen Bouquet',
 '1   tablespoon    red wine vinegar',
 '1       bay leaf',
 '1/8  teaspoon    thyme',
 '3/4  cup    water',
 '1/4  cup    flour']

In [31]:
ingredients_long = (
    df[["id", "name", "ingredients_raw"]]
    .explode("ingredients_raw")
    .rename(columns={"ingredients_raw": "ingredient_raw"})
    .reset_index(drop=True)
)

ingredients_long["ingredient_raw"] = (
    ingredients_long["ingredient_raw"].str.strip()
)

In [32]:
pattern = (
    r"^\s*"
    r"(?P<quantity>\d+\s+\d+/\d+|\d+/\d+|\d+(?:\.\d+)?)?"
    r"\s*"
    r"(?P<unit>cups?|tablespoons?|teaspoons?|ounces?|oz|"
    r"pounds?|lbs?|grams?|g|kilograms?|kg|"
    r"milliliters?|ml|liters?|l|dash(?:es)?)?"
    r"\s*"
    r"(?P<ingredient>.*)"
    r"$"
)

extracted = ingredients_long["ingredient_raw"].str.extract(
    pattern,
    flags=re.IGNORECASE
)

ingredients_long = pd.concat(
    [ingredients_long, extracted],
    axis=1
)

In [35]:
df.head()

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags,is_vegan,is_vegetarian,is_gluten_free,is_dairy_free,is_lactose_free,is_nut_free,is_egg_free,quick_60min,quick_30min,quick_15min,ingredient_raw_count
0,71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","[cherry pie filling, condensed milk, melted ma...","[2 (21 ounce) cans cherry pie filling, 2 ...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False,12
1,76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"[corned beef chopped, sauerkraut cold water, s...","[1/2-1 lb corned beef, cooked and chopped...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False,6
2,503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"[unsalted butter, vegetable oil, all - purpose...","[3/4 cup unsalted butter, at room temperat...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ...",False,False,False,False,False,False,False,False,False,False,13
3,418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"[orange cake mix, instant vanilla pudding, ora...","[1 (18 ounce) pkge.orange cake mix, 1 (3 ...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False,12
4,392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"[butter, brown sugar, granulated sugar, milk, ...","[1/2 cup butter, room temperature , 1/2 c...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,False,True,9

In [39]:
ingredients_long

,id,name,ingredient_raw,quantity,unit,ingredient
0,71247,Cherry Streusel Cobbler,2 (21 ounce) cans cherry pie filling,2,NaN,(21 ounce) cans cherry pie filling
1,71247,Cherry Streusel Cobbler,2 eggs,2,NaN,eggs
2,71247,Cherry Streusel Cobbler,1 (14 ounce) can sweetened condensed milk ...,1,NaN,(14 ounce) can sweetened condensed milk (n...
3,71247,Cherry Streusel Cobbler,1/4 cup melted margarine,1/4,cup,melted margarine
4,71247,Cherry Streusel Cobbler,1/2 teaspoon cinnamon,1/2,teaspoon,cinnamon
...,...,...,...,...,...,...
4722896,510848,Chicken and Dumplings &ndash; Crock Pot,"1 lb chicken, cubed",1,lb,"chicken, cubed"
4722897,510848,Chicken and Dumplings &ndash; Crock Pot,1 lb frozen vegetables,1,lb,frozen vegetables
4722898,510848,Chicken and Dumplings &ndash; Crock Pot,"1 onion, diced",1,NaN,"onion, diced"
4722899,510848,Chicken and Dumplings &ndash; Crock Pot,"24 ounces chicken broth, divided",24,ounces,"chicken broth, divided"
4722900,510848,Chicken and Dumplings &ndash; Crock Pot,1 1/2 cups biscuit mix,1 1/2,cups,biscuit mix

In [44]:
ingredients_long['ingredient'].value_counts().head(100)

ingredient
salt                                  167482
sugar                                  99924
butter                                 63841
water                                  62745
olive oil                              62502
                                       ...
dry mustard                             5206
bay leaves                              5173
packed brown sugar                      5029
salt & freshly ground black pepper      4953
curry powder                            4927
Name: count, Length: 100, dtype: int64

In [46]:
price_list = pd.read_csv('raw_data/precio_por_producto_bilingual.csv')

In [47]:
price_list

       producto     producto ing unit  min_price  max_price  average_price
0        Aceite              Oil   lt      34.50      72.50          44.69
1      Aguacate          Avocado   gr       0.03       0.11           0.07
2           Ajo           Garlic   gr       0.07       0.78           0.39
3      Ajonjoli           Sesame   gr       0.04       0.24           0.16
4     Alcachofa        Artichoke   gr       0.10       0.18           0.15
..          ...              ...  ...        ...        ...            ...
199   Verdolaga         Purslane   gr       0.02       0.10           0.05
200  Villajaiba  Villajaiba Crab   gr       0.12       0.20           0.16
201     Vinagre          Vinegar   lt       9.00      29.90          16.66
202     Yoghurt           Yogurt   gr       0.03       0.40           0.08
203   Zanahoria           Carrot   gr       0.01       0.03           0.02

[204 rows x 6 columns]

In [48]:
ingredients_long["ingredient_key"] = (
    ingredients_long["ingredient"]
    .str.strip()
    .str.lower()
)

price_list["ingredient_key"] = (
    price_list["producto ing"]
    .str.strip()
    .str.lower()
)

In [49]:
ingredients_with_price = ingredients_long.merge(
    price_list[
        ["ingredient_key", "average_price", "unit"]
    ],
    on="ingredient_key",
    how="left"
)

In [53]:
ingredients_with_price.shape

(4723206, 9)

In [54]:
ingredients_with_price['average_price']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
           ..
4723201   NaN
4723202   NaN
4723203   NaN
4723204   NaN
4723205   NaN
Name: average_price, Length: 4723206, dtype: float64

In [57]:
ingredients_with_price[
    ~ingredients_with_price["average_price"].isna()
]['ingredient'].value_counts()

ingredient
sugar               99924
butter              63841
pepper              40951
baking powder       38343
egg                 19304
                    ...
grapefruit              1
prickly pear            1
croaker fish            1
hake                    1
pasteurized milk        1
Name: count, Length: 133, dtype: int64