In [6]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

In [7]:
# menu_semanal from B
# recipes_df
# ingredientes_precios.csv from A
# budget from D

In [8]:
recipes_df = pd.read_csv('raw_data/recipes_clean.csv')
recipes_df

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags,is_vegan,is_vegetarian,is_gluten_free,is_dairy_free,is_lactose_free,is_nut_free,is_egg_free,quick_60min,quick_30min,quick_15min
0,71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","['cherry pie filling', 'condensed milk', 'melt...","['2 (21 ounce) cans cherry pie filling', '...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False
1,76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"['corned beef chopped', 'sauerkraut cold water...","['1/2-1 lb corned beef, cooked and choppe...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False
2,503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"['unsalted butter', 'vegetable oil', 'all - pu...","['3/4 cup unsalted butter, at room tempera...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ...",False,False,False,False,False,False,False,False,False,False
3,418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"['orange cake mix', 'instant vanilla pudding',...","['1 (18 ounce) pkge.orange cake mix', '1 (...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,True,False,False
4,392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"['butter', 'brown sugar', 'granulated sugar', ...","['1/2 cup butter, room temperature ', '1/2...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course...",False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500431,173790,Sausage Meatloaf OAMC,"I grew up on this meatloaf, and I love it. It...","['ground beef', 'ground sausage', 'celery chop...","['1 lb lean ground beef', '1/2 lb gro...","[""Combine ground beef, sausage, celery, onion,...",6.0,1 (244 g),"[""time-to-make"", ""course"", ""main-ingredient"", ...",False,False,False,False,False,False,False,False,False,False
500432,301838,Potato Salad With Olives Capers and Parmesan,Cooking Light.,"['red potatoes', 'fresh ground black pepper', ...","['3 lbs small red potatoes', '2 tablesp...","[""Preheat oven to 375°."", ""To prepare potatoes...",8.0,1 (223 g),"[""time-to-make"", ""course"", ""main-ingredient"", ...",False,True,False,False,False,False,False,False,False,False
500433,130682,Chocolate Banana Pound Cake,"This recipe was passed to me by my mother, and...","['butter', 'brown sugar', 'bananas', 'buttermi...","['1 cup butter (room temperature)', '2 ...","[""Preheat oven to 350 degrees."", ""Grease and f...",24.0,1 (99 g),"[""time-to-make"", ""course"", ""main-ingredient"", ...",False,False,False,False,False,False,False,False,False,False
500434,353659,Cheesy Ground Beef and Rice Casserole,This is one of those comfort food dishes I cre...,"['ground beef', 'medium onion chopped', 'brown...","['1 1/2 lbs ground beef', '1 medium o...","[""*What I mean by ""partly drained"" with the mu...",6.0,1 (394 g),"[""60-minutes-or-less"", ""time-to-make"", ""prepar...",False,False,False,False,False,False,False,True,False,False
500435,510848,Chicken and Dumplings &ndash; Crock Pot,Fix it and Forget it Lightly – Slow Cooker rec...,"['chicken cubed', 'frozen vegetables', 'onion'...","['1 lb chicken, cubed ', '1 lb froze...","[""Combine chicken, vegetables, onion and chick...",6.0,1 (323 g),"[""course"", ""preparation"", ""5-ingredients-or-le...",False,False,False,False,False,False,False,False,False,False

In [9]:
#Preparar ingredients_precios.csv inventado con 10-15 ingredientes y precios - Completado
prices_df = pd.read_csv('raw_data/ingredient_prices_v1.csv')
prices_df = prices_df.drop_duplicates(
    subset=["ingredient", "store"]
).reset_index(drop=True)
prices_df

     ingredient profeco_category   price unit                  store
0       almonds        Almendras  398.67   kg                Alsuper
1       almonds        Almendras  500.00   kg         Bodega Aurrera
2       almonds        Almendras  200.00   kg      Central de Abasto
3       almonds        Almendras  440.00   kg               Chedraui
4       almonds        Almendras  440.00   kg       Chedraui Selecto
...         ...              ...     ...  ...                    ...
3270   zucchini         Calabaza   34.00   kg            Superissste
3271   zucchini         Calabaza   19.90   kg  Supermercado Gonzalez
3272   zucchini         Calabaza   19.55   kg               U.n.a.m.
3273   zucchini         Calabaza   36.90   kg               Wal-mart
3274   zucchini         Calabaza   36.90   kg       Wal-mart Express

[3275 rows x 5 columns]

In [10]:
menu_sample = {
    "monday": [503816],
    "tuesday": [71247],
    "wednesday": [418749],
    "thursday": [130682],
    "friday": [76133],
    "saturday": [392934],
    "sunday": [173790]
}

In [11]:
ingredients_raw_sample = pd.read_csv('raw_data/recipe_ingredients_raw_sample.csv')
ingredients_raw_sample

        id      name    ingredient  quantity
0   503816  huanying          milk         1
1   503816  huanying        tomato        20
2   503816  huanying           egg        20
3    71247     nihao  cream cheese         2
4    71247     nihao        celery         3
5    71247     nihao       avocado         5
6    71247     nihao         honey         6
7   418749    xiexie        butter         3
8   130682    haochi      cinnamon         2
9   130682    haochi   green onion         3
10   76133    haowan           egg         6
11   76133    haowan        carrot        19
12   76133    haowan  black pepper        20
13  392934  buzhidao         onion         2
14  173790     chiba     margarine         1
15  173790   lewagon       vanilla         6
16  234566    meiyou       vanilla         3

In [12]:
def get_ingredients_from_menu(
    menu_semanal,
    recipes_df
):
    recipe_ids = [
        recipe_id
        for daily_ids in menu_semanal.values()
        for recipe_id in daily_ids
    ]

    ingredients_list = []

    for recipe_id in recipe_ids:
        recipe_ingredients = (
            recipes_df.loc[
                recipes_df["id"] == recipe_id,
                ["ingredient", "quantity"]
            ]
            .dropna(subset=["ingredient"])
            .to_dict(orient="records")
        )

        ingredients_list.extend(recipe_ingredients)

    return ingredients_list

In [13]:
ingredients_list = get_ingredients_from_menu(
    menu_sample,
    ingredients_raw_sample
)

ingredients_list

[{'ingredient': 'milk', 'quantity': 1},
 {'ingredient': 'tomato', 'quantity': 20},
 {'ingredient': 'egg', 'quantity': 20},
 {'ingredient': 'cream cheese', 'quantity': 2},
 {'ingredient': 'celery', 'quantity': 3},
 {'ingredient': 'avocado', 'quantity': 5},
 {'ingredient': 'honey', 'quantity': 6},
 {'ingredient': 'butter', 'quantity': 3},
 {'ingredient': 'cinnamon', 'quantity': 2},
 {'ingredient': 'green onion', 'quantity': 3},
 {'ingredient': 'egg', 'quantity': 6},
 {'ingredient': 'carrot', 'quantity': 19},
 {'ingredient': 'black pepper', 'quantity': 20},
 {'ingredient': 'onion', 'quantity': 2},
 {'ingredient': 'margarine', 'quantity': 1},
 {'ingredient': 'vanilla', 'quantity': 6}]

In [14]:
def aggregate_ingredients(ingredients_list):
    ingredients_df = pd.DataFrame(ingredients_list)

    ingredients_df["ingredient"] = (
        ingredients_df["ingredient"]
        .str.lower()
        .str.strip()
    )

    ingredients_df["quantity"] = pd.to_numeric(
        ingredients_df["quantity"],
        errors="coerce"
    )

    aggregated_ingredients = (
        ingredients_df
        .dropna(subset=["ingredient", "quantity"])
        .groupby(
            "ingredient",
            as_index=False
        )
        .agg(
            quantity=("quantity", "sum"),
            recipe_appearances=("ingredient", "size")
        )
    )

    return aggregated_ingredients

In [15]:
aggregated_ingredients = aggregate_ingredients(
    ingredients_list
)

aggregated_ingredients

      ingredient  quantity  recipe_appearances
0        avocado         5                   1
1   black pepper        20                   1
2         butter         3                   1
3         carrot        19                   1
4         celery         3                   1
5       cinnamon         2                   1
6   cream cheese         2                   1
7            egg        26                   2
8    green onion         3                   1
9          honey         6                   1
10     margarine         1                   1
11          milk         1                   1
12         onion         2                   1
13        tomato        20                   1
14       vanilla         6                   1

In [16]:
selected_store = "Chedraui"
store_prices = prices_df[
    prices_df["store"] == selected_store
].copy()

store_prices

                ingredient profeco_category   price   unit     store
3                  almonds        Almendras  440.00     kg  Chedraui
36                   apple          Manzana   48.00     kg  Chedraui
76               artichoke        Alcachofa  179.00     kg  Chedraui
94                 avocado         Aguacate   59.00     kg  Chedraui
135                  bacon   Tocino Ahumado  344.00     kg  Chedraui
...                    ...              ...     ...    ...       ...
3100               walnuts             Nuez  706.67     kg  Chedraui
3135                 water     Agua Sin Gas   12.00  litro  Chedraui
3174     whole kernel corn  Granos de Elote  116.00     kg  Chedraui
3203  worcestershire sauce    Salsa Inglesa  272.41  litro  Chedraui
3241              zucchini         Calabaza   32.50     kg  Chedraui

[95 rows x 5 columns]

In [17]:
cart = aggregated_ingredients.merge(
    store_prices[
        [
            "ingredient",
            "profeco_category",
            "price",
            "unit",
            "store"
        ]
    ],
    on="ingredient",
    how="left",
    validate="one_to_one"
)

cart

,ingredient,quantity,recipe_appearances,profeco_category,price,unit,store
0,avocado,5,1,Aguacate,59.00,kg,Chedraui
1,black pepper,20,1,NaN,NaN,NaN,NaN
2,butter,3,1,Mantequilla,271.11,kg,Chedraui
3,carrot,19,1,Zanahoria,15.50,kg,Chedraui
4,celery,3,1,Apio,29.20,kg,Chedraui
5,cinnamon,2,1,Canela,966.67,kg,Chedraui
6,cream cheese,2,1,NaN,NaN,NaN,NaN
7,egg,26,2,Huevo,2.33,pieza,Chedraui
8,green onion,3,1,Cebolla,14.50,manojo,Chedraui
9,honey,6,1,Miel de Abeja,192.54,kg,Chedraui
10,margarine,1,1,Margarina,200.00,kg,Chedraui
11,milk,1,1,Leche Pasteurizada,33.00,litro,Chedraui
12,onion,2,1,Cebolla,28.00,kg,Chedraui
13,tomato,20,1,Jitomate,23.45,kg,Chedraui
14,vanilla,6,1,Vainilla,104.00,litro,Chedraui

In [18]:
cart["cost"] = (
    cart["quantity"]
    * cart["price"]
).round(2)
cart

,ingredient,quantity,recipe_appearances,profeco_category,price,unit,store,cost
0,avocado,5,1,Aguacate,59.00,kg,Chedraui,295.00
1,black pepper,20,1,NaN,NaN,NaN,NaN,NaN
2,butter,3,1,Mantequilla,271.11,kg,Chedraui,813.33
3,carrot,19,1,Zanahoria,15.50,kg,Chedraui,294.50
4,celery,3,1,Apio,29.20,kg,Chedraui,87.60
5,cinnamon,2,1,Canela,966.67,kg,Chedraui,1933.34
6,cream cheese,2,1,NaN,NaN,NaN,NaN,NaN
7,egg,26,2,Huevo,2.33,pieza,Chedraui,60.58
8,green onion,3,1,Cebolla,14.50,manojo,Chedraui,43.50
9,honey,6,1,Miel de Abeja,192.54,kg,Chedraui,1155.24
10,margarine,1,1,Margarina,200.00,kg,Chedraui,200.00
11,milk,1,1,Leche Pasteurizada,33.00,litro,Chedraui,33.00
12,onion,2,1,Cebolla,28.00,kg,Chedraui,56.00
13,tomato,20,1,Jitomate,23.45,kg,Chedraui,469.00
14,vanilla,6,1,Vainilla,104.00,litro,Chedraui,624.00

In [19]:
total_cost = round(
    float(cart["cost"].sum()),
    2
)

print("Total cost:", total_cost)

Total cost: 6065.09

In [20]:
missing_ingredients = (
    cart.loc[
        cart["price"].isna(),
        "ingredient"
    ]
    .tolist()
)

print(
    "Ingredients without price:",
    missing_ingredients
)

Ingredients without price: ['black pepper', 'cream cheese']

In [21]:
from frente_c import calculate_cost

In [22]:
calculate_cost(aggregated_ingredients,prices_df,selected_store)

(      ingredient  quantity  recipe_appearances    profeco_category   price  \
 0        avocado         5                   1            Aguacate   59.00
 1   black pepper        20                   1                 NaN     NaN
 2         butter         3                   1         Mantequilla  271.11
 3         carrot        19                   1           Zanahoria   15.50
 4         celery         3                   1                Apio   29.20
 5       cinnamon         2                   1              Canela  966.67
 6   cream cheese         2                   1                 NaN     NaN
 7            egg        26                   2               Huevo    2.33
 8    green onion         3                   1             Cebolla   14.50
 9          honey         6                   1       Miel de Abeja  192.54
 10     margarine         1                   1           Margarina  200.00
 11          milk         1                   1  Leche Pasteurizada   33.00
 12         onion         2                   1             Cebolla   28.00
 13        tomato        20                   1            Jitomate   23.45
 14       vanilla         6                   1            Vainilla  104.00

       unit     store     cost
 0       kg  Chedraui   295.00
 1      NaN       NaN      NaN
 2       kg  Chedraui   813.33
 3       kg  Chedraui   294.50
 4       kg  Chedraui    87.60
 5       kg  Chedraui  1933.34
 6      NaN       NaN      NaN
 7    pieza  Chedraui    60.58
 8   manojo  Chedraui    43.50
 9       kg  Chedraui  1155.24
 10      kg  Chedraui   200.00
 11   litro  Chedraui    33.00
 12      kg  Chedraui    56.00
 13      kg  Chedraui   469.00
 14   litro  Chedraui   624.00  ,
 6065.09,
 ['black pepper', 'cream cheese'])